### ISSUE TITLE
[BUG] Anti SpeedHack

### ISSUE THREAD

**Issue by Drmohammad11** [Silenci0/SMAC#15]
hi
this plugin detect players for using speed hack, why don't ban players ??
`Hackworth (ID: STEAM_0:0:1234567890 | IP: 123.123.123.123) is suspected of using a speedhack.
`maybe this false or  ... ?

**Comment by borzaka** [comment]
I have multiple detections like this. Quote from the [Anti-Speedhack Wiki page](https://github.com/Silenci0/SMAC/wiki/Anti-Speedhack).

> Be aware that a client lagging severely can mimic the effects of a speedhack, and as a result, this module will not take action on clients other than slowing them down.

So they are probably just lagging from time to time.

**Comment by Drmohammad11** [comment]
> I have multiple detections like this. Quote from the [Anti-Speedhack Wiki page](https://github.com/Silenci0/SMAC/wiki/Anti-Speedhack).
> 
> > Be aware that a client lagging severely can mimic the effects of a speedhack, and as a result, this module will not take action on clients other than slowing them down.
> 
> So they are probably just lagging from time to time.

all right. thank you!
