### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by SadBeYou** [Silenci0/SMAC#2]
L 03/06/2019 - 03:26:47: [SM] Exception reported: PLUGIN STOPPED - Reason: No config entry found for 'ssh' in databases.cfg - PLUGIN STOPPED
L 03/06/2019 - 03:26:47: [SM] Blaming: ssh.smx
L 03/06/2019 - 03:26:47: [SM] Call stack trace:
L 03/06/2019 - 03:26:47: [SM]   [0] SetFailState
L 03/06/2019 - 03:26:47: [SM]   [1] Line 510, ssh.sp::SQL_Connector
L 03/06/2019 - 03:26:47: [SM]   [2] Line 217, ssh.sp::OnPluginStart
L 03/06/2019 - 03:26:47: [SM] Unable to load plugin "ssh.smx": Error detected in plugin startup (see error logs)

**Comment by Silenci0** [comment]
Hello, 

Are you sure this is the correct plugin that you are commenting on? Its named ssh.smx and none of the current SMAC plugins are named this. If its a recompiled plugin that you've renamed, you might want to let me know which code files your plugin is referring to.

However, regardless of if this is the correct plugin or not, judging from the error, it looks like databases.cfg does not have any of the required database information within it that the plugin requires. I think you'll need to look over your databases.cfg file and add the appropriate information for ssh.smx

**Comment by SadBeYou** [comment]
nvm wong site lol remove post thank you

**Comment by Silenci0** [comment]
No problem, it happens. I'll be closing this then.
