### ISSUE TITLE
sv_occlude_players

### ISSUE THREAD

**Issue by bubobih** [Silenci0/SMAC#25]
Hello i have strange problem after latest update.... 

L 11/21/2019 - 11:58:37: Info (map "de_dust2") (file "/home/dust2_new/csgo/addons/sourcemod/logs/errors_20191121.log")
L 11/21/2019 - 11:58:37: [SM] Failed to load plugin "smac/smac_wallhack.smx": This module is disabled for this game. Enable "sv_occlude_players" for the same feature..
L 11/21/2019 - 11:58:45: Error log file session closed.

[SM] Value of cvar "sv_occlude_players": "1"

**Comment by caxanga334** [comment]
I'm assuming you're using CSGO. If that's the case then don't use the wallhack module, it's obsolete. Use the built-in anti wallhack by setting sv_occlude_players to 1.

**Comment by bubobih** [comment]
yes its csgo :P ok tnx for the info
