### ISSUE TITLE
Question cvars plugin

### ISSUE THREAD

**Issue by lunatixxx** [Silenci0/SMAC#34]
If add a cvar to server.cfg is it protected automatically ? Or do i have to add it manually into smac.cfg with "smac_addcvar cvar comparison type action value" ?

**Comment by Silenci0** [comment]
If you are asking whether or not the plugin automatically protects a cvar found in server.cfg, then no it does not. To list a cvar as protected by the plugin, you will need to add it to server.cfg (you can also put this in in smac.cfg or sourcemod.cfg if you'd rather put them there instead) formatted like so:

`smac_addcvar <cvar> <comparison type> <action> <value> <value2 if bound>`

Each cvar you want protected/monitored will need its own line, so you cannot add multiple cvars to "smac_addcvar". Value 2 is not necessary for most cvars unless using the "between" comparison type. You can find the comparison and action types on the wiki here: https://github.com/Silenci0/SMAC/wiki/ConVar-Checker

**Comment by lunatixxx** [comment]
If i want to protect a "sv_thing" cvar, i guess the correct comparison is "replicate" then. Thanks
