### ISSUE TITLE
Anti Speedhack bypass

### ISSUE THREAD

**Issue by lunatixxx** [Silenci0/SMAC#35]
Usually the anti speedhack plugin does a good job at blocking this kind of cheat, but it looks like it can be bypassed now (L4D2). At least it detected the cheater but the plugin was not able to block it, the player had a VAC ban on his profile already so it is confirmed cheat. 
Basically he teleported me with his jockey out of the map, the detection came after delayed.

Video link : https://streamable.com/ypcg3

02/01/2020 - 05:57:08: [smac_speedhack.smx | 0.8.7.2] riley (ID: STEAM_1:1:418677735 | IP: 72.143.253.188) is suspected of using speedhack.
	Map: c1m1_hotel | Origin: 0 0 0 | Angles: 6 83 0 | Weapon: weapon_jockey_claw | Team: 3 | Latency: 140ms

**Comment by borzaka** [comment]
The [Anti Speedhack](https://github.com/Silenci0/SMAC/wiki/Anti-Speedhack) module is disabled by default, because it detects lags as speed hacking, and it would cause many false positives. Of course it detects true speedhackers, but because it's disabled by default, it will just leave a notify in the logs.

**Comment by lunatixxx** [comment]
> 
"This module checks for abnormal speeds on clients and attempts to block them. It runs passively in the background to prevent speedhacks from working. Be aware that a client lagging severely can mimic the effects of a speedhack, and as a result, this module will not take action on clients other than slowing them 
> down."

It does work actually many cheaters was wondering why their speedhack wasn't functionning, this was confirmed by the aimbot detection who followed. I don't even remember having a false positive with this plugin, this must be 99% right i will say.

**Comment by CanadianJeff** [comment]
on my server a player was standing still and later incap the SMAC was saying he was speedhacking while on the ground not even moving

**Comment by borzaka** [comment]
From the [wiki](https://github.com/Silenci0/SMAC/wiki/Anti-Speedhack):

> This module checks for abnormal speeds on clients and attempts to block them. It runs passively in the background to prevent speedhacks from working, as well as notifying admins if a player is suspected of using such a cheat.
> 
> Be aware that a client lagging severely can mimic the effects of a speedhack, and as a result, this module will not take action on clients other than slowing them down.

**Comment by lunatixxx** [comment]
I had recently something similar who happened with the survivor taken by the jockey again, teleported under the map but it did not trigger a detection. So while  i'm not skeptical on the fact the profile i mentioned was a cheater this still make me wonder what kind of bug this is, something related to collision bug in the map or maybe the tickrate ? Just to let you know even if this plugin is outdated anyway.

**Comment by CanadianJeff** [comment]
the teleporting jockey is a common problem and has been for several years now

**Comment by lunatixxx** [comment]
From what i understand it is a cheat named airstuck teleportation. Why nobody tried to patch or detect it ?
