### ISSUE TITLE
[New Features] Profile status checker

### ISSUE THREAD

**Issue by Drmohammad11** [Silenci0/SMAC#5]
hi !!
thank you for update!!
can you added profile checker ?
i need for blocking new accounts :(

thank you

**Comment by Silenci0** [comment]
Hello,

This feature, assuming you mean steam profile checking, is sort of beyond the scope of SMAC as it is a server anti-cheat, not a profile blocker. Having SMAC look up and ban new accounts would require a significant amount of work and would need SteamAPI integration/support to be added, none of which I am willing to do for this fork of SMAC, at least not at this time.

That said, there might be a plugin similar to this one: https://github.com/RumbleFrog/Anti-Private that might be able to do what you need. You might want to search/ask on the alliedmodder's Sourcemod forums if someone has created a plugin to this or to ask if someone could make this for you as a number of coders do frequent those forums and some of them might be able to help you with this, assuming it is possible. 

Silence

**Comment by Drmohammad11** [comment]
all right, can you help me for this feature??
https://forums.alliedmods.net/showthread.php?t=315546

plugin CowAntiCheat have a profile status checker but dont work :((
 my server have new players with cheat
 he ban from my server but he create new account  and use cheat again :((
please help me.
sorry for bad speak english!!

**Comment by Silenci0** [comment]
Sorry, but I am unable to help with this feature for that plugin as I would need to know more about SteamWorks API. I will keep this feature in mind going forward, but at this time, I am unable to assist.

**Comment by Drmohammad11** [comment]
ok. no problem my freind.

**Comment by ConnorBP** [comment]
steamworks api isn't too bad tbh. The docs on it are extremely easy too. Assuming you can bind to a dll library all you need to do is call their built in functions

**Comment by Drmohammad11** [comment]
@ConnorBP 
can you help me for this feature??
https://forums.alliedmods.net/showthread.php?t=315546

**Comment by Silenci0** [comment]
I will be closing this issue. For now, this feature will not be added to this fork of SMAC.
