### ISSUE TITLE
if clients set sv_cheats 1 they get banned

### ISSUE THREAD

**Issue by CanadianJeff** [Silenci0/SMAC#52]
I was testing this the other day and set sv_cheats 1 in my developer console and got the ban message that I was kicked for a cheating infraction maybe we could update this plugin to not kick/ban people who are admins on the server but still log in console or smac log file that the admin has sv_cheats set to 1

https://github.com/Silenci0/SMAC/blob/c60d909cb53bf31324d3a73694b219b9eb58d050/addons/sourcemod/scripting/smac_cvars.sp#L618

just a thought

**Comment by borzaka** [comment]
There was a discussion about this. And the agreement was that no exceptions, and no while list, because it's breaks the purpose of the plugin.
So, if you want to practice with `sv_cheats`, you should disable the plugin.

**Comment by CanadianJeff** [comment]
that is what have been doing I guess I could always fork this code and setup a check for admin and prevent kicks/bans

**Comment by CanadianJeff** [comment]
issue has been resolved by using the plugin that gives admins immune
